version: '3.7'

services:
  server:
    restart: always
    container_name: server
    build:
      context: ./server
      dockerfile: $PWD/server/Dockerfile
    volumes:
      - ./server:/usr/src/app
    ports:
      - "8080:8080"

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: $PWD/client/Dockerfile
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=vidcheck

volumes:
  postgres_data:
