// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analysis": {
            "post": {
                "description": "Create videoAnalysis",
                "tags": [
                    "VideoAnalysis"
                ],
                "summary": "Create videoAnalysis",
                "operationId": "add-video-analysis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organisation ID",
                        "name": "X-Organisation",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Video Analysis Api Data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/videoanalysis.videoAnalysisApiData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Analysis"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/analysis/video/{video_id}/analysis/{video_analysis_id}": {
            "get": {
                "description": "Get videosAnalysis by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VideoAnalysis"
                ],
                "summary": "Show a videosAnalysis by id",
                "operationId": "get-video-analysis-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organisation ID",
                        "name": "X-Organisation",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Video ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Video Analysis ID",
                        "name": "video_analysis_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Analysis"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update videosAnalysis by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VideoAnalysis"
                ],
                "summary": "Update a videosAnalysis by id",
                "operationId": "update-video-analysis-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organisation ID",
                        "name": "X-Organisation",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Video ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Video Analysis ID",
                        "name": "video_analysis_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Video Analysis Data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/videoanalysis.videoAnalysis"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Analysis"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete videoAnalysis by id",
                "tags": [
                    "VideoAnalysis"
                ],
                "summary": "Delete a videoAnalysis by id",
                "operationId": "delete-video-analysis-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organisation ID",
                        "name": "X-Organisation",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Video ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Video Analysis ID",
                        "name": "video_analysis_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/analyse": {
            "get": {
                "description": "Show all video analysis",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "VideoAnalysis"
                ],
                "summary": "Show all video analysis",
                "operationId": "get-all-video-analysis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organisation ID",
                        "name": "X-Organisation",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "limt per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/videoanalysis.paging"
                        }
                    }
                }
            }
        },
        "/claimants": {
            "get": {
                "description": "Get all claimants",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Claimant"
                ],
                "summary": "Show all claimants",
                "operationId": "get-all-claimants",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "limit per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/claimant.paging"
                        }
                    }
                }
            },
            "post": {
                "description": "Create claimant",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Claimant"
                ],
                "summary": "Create claimant",
                "operationId": "add-claimant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Claimant Object",
                        "name": "Claimant",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/claimant.claimant"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Claimant"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/claimants/{claimant_id}": {
            "get": {
                "description": "Get claimant by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Claimant"
                ],
                "summary": "Show a claimant by id",
                "operationId": "get-claimant-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Claimant ID",
                        "name": "claimant_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Claimant"
                        }
                    }
                }
            },
            "put": {
                "description": "Update claimant by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Claimant"
                ],
                "summary": "Update a claimant by id",
                "operationId": "update-claimant-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Claimant ID",
                        "name": "claimant_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Claimant",
                        "name": "Claimant",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/claimant.claimant"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Claimant"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete claimant by ID",
                "tags": [
                    "Claimant"
                ],
                "summary": "Delete a claimant",
                "operationId": "delete-claimant-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Claimant ID",
                        "name": "claimant_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/ratings": {
            "get": {
                "description": "Get all ratings",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rating"
                ],
                "summary": "Show all ratings",
                "operationId": "get-all-ratings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "limit per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rating.paging"
                        }
                    }
                }
            },
            "post": {
                "description": "Create rating",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rating"
                ],
                "summary": "Create rating",
                "operationId": "add-rating",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Rating Object",
                        "name": "Rating",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rating.rating"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Rating"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ratings/default": {
            "post": {
                "description": "Create Default Ratings",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rating"
                ],
                "summary": "Create Default Ratings",
                "operationId": "add-default-ratings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Rating"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ratings/{rating_id}": {
            "get": {
                "description": "Get rating by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rating"
                ],
                "summary": "Show a rating by id",
                "operationId": "get-rating-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rating ID",
                        "name": "rating_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Rating"
                        }
                    }
                }
            },
            "put": {
                "description": "Update rating by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rating"
                ],
                "summary": "Update a rating by id",
                "operationId": "update-rating-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rating ID",
                        "name": "rating_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rating",
                        "name": "Rating",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/rating.rating"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Rating"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete rating by ID",
                "tags": [
                    "Rating"
                ],
                "summary": "Delete a rating",
                "operationId": "delete-rating-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rating ID",
                        "name": "rating_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/spaces": {
            "get": {
                "description": "Get all spaces",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Space"
                ],
                "summary": "Show all spaces",
                "operationId": "get-all-spaces",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/space.orgWithSpace"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create space",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Space"
                ],
                "summary": "Create space",
                "operationId": "add-space",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Space Object",
                        "name": "Space",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/space.space"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Space"
                        }
                    }
                }
            }
        },
        "/spaces/{space_id}": {
            "put": {
                "description": "Update space",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Space"
                ],
                "summary": "Update space",
                "operationId": "update-space",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "space_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Space Object",
                        "name": "Space",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/space.space"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Space"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete space",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Space"
                ],
                "summary": "Delete space",
                "operationId": "delete-space",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "space_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/videos": {
            "get": {
                "description": "Get all videos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Videos"
                ],
                "summary": "Show all videos",
                "operationId": "get-all-videos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "limt per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/video.paging"
                        }
                    }
                }
            },
            "post": {
                "description": "Create video",
                "tags": [
                    "Videos"
                ],
                "summary": "Create video",
                "operationId": "add-video",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Video Analysis Api Data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/video.videoanalysisReqData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/video.videoanalysisData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/videos/{video_id}": {
            "get": {
                "description": "Get video by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Videos"
                ],
                "summary": "Show a video by id",
                "operationId": "get-video by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Video ID",
                        "name": "video_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/video.videoanalysisData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Update video by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Videos"
                ],
                "summary": "Update a video by id",
                "operationId": "update-video-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Video ID",
                        "name": "video_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Video Analysis Api Data",
                        "name": "Data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/video.videoanalysisReqData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Video"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete video by ID",
                "tags": [
                    "Videos"
                ],
                "summary": "Delete a video",
                "operationId": "delete-video-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Video ID",
                        "name": "video_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/videos/{video_id}/published": {
            "get": {
                "description": "Get published video by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Videos"
                ],
                "summary": "Show a published video by id",
                "operationId": "get-published-video-by-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "X-User",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Space ID",
                        "name": "X-Space",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Video ID",
                        "name": "video_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/video.videoanalysisData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "claimant.claimant": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "tag_line": {
                    "type": "string"
                }
            }
        },
        "claimant.paging": {
            "type": "object",
            "properties": {
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Claimant"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.Analysis": {
            "type": "object",
            "properties": {
                "checked_date": {
                    "type": "string"
                },
                "claim": {
                    "type": "string"
                },
                "claim_date": {
                    "type": "string"
                },
                "claim_sources": {
                    "type": "string"
                },
                "claimant": {
                    "$ref": "#/definitions/model.Claimant"
                },
                "claimant_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_time": {
                    "type": "integer"
                },
                "end_time_fraction": {
                    "type": "number"
                },
                "fact": {
                    "type": "string"
                },
                "html": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_claim": {
                    "type": "boolean"
                },
                "rating": {
                    "$ref": "#/definitions/model.Rating"
                },
                "rating_id": {
                    "type": "integer"
                },
                "review_sources": {
                    "type": "string"
                },
                "start_time": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "video": {
                    "$ref": "#/definitions/model.Video"
                },
                "video_id": {
                    "type": "integer"
                }
            }
        },
        "model.Claimant": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "space_id": {
                    "type": "integer"
                },
                "tag_line": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.Rating": {
            "type": "object",
            "properties": {
                "colour": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "numeric_value": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                },
                "space_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.Space": {
            "type": "object",
            "properties": {
                "contact_info": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "organisation_id": {
                    "type": "integer"
                },
                "site_address": {
                    "type": "string"
                },
                "site_title": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "social_media_urls": {
                    "type": "string"
                },
                "tag_line": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "verification_codes": {
                    "type": "string"
                }
            }
        },
        "model.Video": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "space_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "video_type": {
                    "type": "string"
                }
            }
        },
        "rating.paging": {
            "type": "object",
            "properties": {
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Rating"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "rating.rating": {
            "type": "object",
            "required": [
                "name",
                "numeric_value"
            ],
            "properties": {
                "colour": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "numeric_value": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "space.orgWithSpace": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "permission": {
                    "$ref": "#/definitions/space.organisationUser"
                },
                "slug": {
                    "type": "string"
                },
                "spaces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Space"
                    }
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "space.organisationUser": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "space.space": {
            "type": "object",
            "required": [
                "name",
                "organisation_id"
            ],
            "properties": {
                "contact_info": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organisation_id": {
                    "type": "integer"
                },
                "site_address": {
                    "type": "string"
                },
                "site_title": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "social_media_urls": {
                    "type": "string"
                },
                "tag_line": {
                    "type": "string"
                },
                "verification_codes": {
                    "type": "string"
                }
            }
        },
        "video.paging": {
            "type": "object",
            "properties": {
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/video.videoanalysisData"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "video.video": {
            "type": "object",
            "required": [
                "title",
                "url",
                "video_type"
            ],
            "properties": {
                "status": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "total_duration": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                },
                "video_type": {
                    "type": "string"
                }
            }
        },
        "video.videoanalysis": {
            "type": "object",
            "required": [
                "claimant_id",
                "end_time",
                "end_time_fraction",
                "rating_id"
            ],
            "properties": {
                "checked_date": {
                    "type": "string"
                },
                "claim": {
                    "type": "string"
                },
                "claim_date": {
                    "type": "string"
                },
                "claim_sources": {
                    "type": "string"
                },
                "claimant_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "end_time": {
                    "type": "integer"
                },
                "end_time_fraction": {
                    "type": "number"
                },
                "fact": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_claim": {
                    "type": "boolean"
                },
                "rating_id": {
                    "type": "integer"
                },
                "review_sources": {
                    "type": "string"
                },
                "start_time": {
                    "type": "integer"
                }
            }
        },
        "video.videoanalysisData": {
            "type": "object",
            "properties": {
                "analysis": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Analysis"
                    }
                },
                "video": {
                    "$ref": "#/definitions/model.Video"
                }
            }
        },
        "video.videoanalysisReqData": {
            "type": "object",
            "required": [
                "analysis",
                "video"
            ],
            "properties": {
                "analysis": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/video.videoanalysis"
                    }
                },
                "video": {
                    "$ref": "#/definitions/video.video"
                }
            }
        },
        "videoanalysis.paging": {
            "type": "object",
            "properties": {
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Analysis"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "videoanalysis.video": {
            "type": "object",
            "required": [
                "title",
                "url",
                "video_type"
            ],
            "properties": {
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "video_type": {
                    "type": "string"
                }
            }
        },
        "videoanalysis.videoAnalysis": {
            "type": "object",
            "required": [
                "end_time",
                "end_time_fraction",
                "rating_id"
            ],
            "properties": {
                "checked_date": {
                    "type": "string"
                },
                "claim": {
                    "type": "string"
                },
                "claim_date": {
                    "type": "string"
                },
                "claim_sources": {
                    "type": "string"
                },
                "end_time": {
                    "type": "integer"
                },
                "end_time_fraction": {
                    "type": "number"
                },
                "fact": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_claim": {
                    "type": "boolean"
                },
                "rating_id": {
                    "type": "integer"
                },
                "review_sources": {
                    "type": "string"
                },
                "start_time": {
                    "type": "integer"
                }
            }
        },
        "videoanalysis.videoAnalysisApiData": {
            "type": "object",
            "required": [
                "analysis",
                "video"
            ],
            "properties": {
                "analysis": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/videoanalysis.videoAnalysis"
                    }
                },
                "video": {
                    "$ref": "#/definitions/videoanalysis.video"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:7740",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "VidCheck API",
	Description: "VidCheck server API",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
