selfservice:
  strategies:
    password:
      enabled: true

  verify:
    return_to: http://127.0.0.1:4455/

  logout:
    redirect_to: http://127.0.0.1:4455/.factly/kavach/web/auth/login

  login:
    request_lifespan: 10m

  registration:
    request_lifespan: 10m
    after:
      password:
        hooks:
          - hook: session

log:
  level: debug

secrets:
  session:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE

urls:
  login_ui: http://127.0.0.1:4455/.factly/kavach/web/auth/login
  registration_ui: http://127.0.0.1:4455/.factly/kavach/web/auth/registration
  error_ui: http://127.0.0.1:4455/.factly/kavach/web/error
  settings_ui: http://127.0.0.1:4455/.factly/kavach/web/password
  verify_ui: http://127.0.0.1:4455/.factly/kavach/web/verify

  self:
    public: http://127.0.0.1:4455/.ory/kratos/public/
    admin: http://kratos:4434/
  default_return_to: http://127.0.0.1:4455/.factly/kavach/web/

hashers:
  argon2:
    parallelism: 1
    memory: 131072
    iterations: 2
    salt_length: 16
    key_length: 16

identity:
  traits:
    default_schema_url: file:///etc/config/kratos/identity.traits.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
