name: Server Releaser
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Login Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u deshetti --password-stdin
    - name: Build and push vidcheck server
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: factly/vidcheck-server:${{ env.RELEASE_VERSION }}
        context: server
        file: client/Dockerfile.prod